language: node_js
node_js:
- 14
services:
- postgresql
addons:
  postgresql: '10'
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "GraceShopper-test";' -U postgres
script:
- npm test
- npm run build-client
deploy:
  api_key:
    secure: GNZvEG+9XlYcX6xuxxdMhM2mSN5I3rCqUtN0WBwAgMcZ/e09zqsZWrFAWxlv//6ESiVAVB5saqPWHCvj5CgMcVvk1JQ3iDUmFWBzZW6Z7vZNwppamz1x0Q/HGLaR67eiQ5cRtPaHzwRdXIqX75ZKNedzTm8B9D/x5MQZhDu7TP+fsx9lWNJfu2gUJFyInf/zOLzhSH0JS91EU4GICtkEZqYcg/1VeCr3f0rSY+6DUR9wi8wEPsLCO/U4ars7HgFMCRm4+jnXgeOeYv41pxpqCdSodfNP58ss8ZFQwln1aITx4p6LCe8vkjZq4NwvrLIxdmnhHXmeT42rzH7r9RTuK6kEVpIDFN2KvN9PJac4oPt7p42wOrTJeRSZqp3CtgaNwaq/NMN17rG7oEfK/lTYu073/ETWdjk+1lg8lMEvg0pKxxqfr48z91DPaeRYW3itYCzHTG+MqlLW+S1h2npqJ++/+dG8IYFw5WRWG+ob5d8pJP0At18dNPpUBLROhRSQkGKP/+kmLzGjfG1ZfcgjURX+XgYsyKgTIwuCHy2j62Je5QRRSAO7oBOstfgMgIcX2K0g3SQchsi9lrtrMFcLXN8k++N3pIAkqs39NTQ1+41+rjXKEfsqcFKOej13j7NjBJ1fwJYNwitbNS7VBX4mVwRb5EpMsa69n5GWG7L49vI=
